### Listar todas as tarefas
GET http://localhost:5000/api/tarefas/listar

### Cadastrar uma nova tarefa
POST http://localhost:5000/api/tarefas/cadastrar
Content-Type: application/json

{
    "titulo": "Estudar Node.js",
    "descricao": "Estudar Node.js para desenvolver aplicações web",
    "categoriaId": "6d091456-5a2f-4b5a-98fc-f1a3b50a627d"
}
### Alterar uma tarefa
PUT http://localhost:5000/api/tarefas/alterar/e5d4a7b9-1f9e-4c4a-ae3b-5b7c1a9d2e3f

###
GET http://localhost:5000/api/tarefas/naoconcluidas
###
GET http://localhost:5000/api/tarefas/concluidas
